export interface StudentCodename {
    name: string;
    alias: string;
}

export const studentCodenames: StudentCodename[] = [
    { name: 'Ashley Ganesh', alias: 'CashMoney' },
    { name: 'Aminata Davis', alias: 'SolarPenguin' },
    { name: 'Emily Figueroa', alias: 'machi25' },
    { name: 'Bennett Galin', alias: 'Avalanche12' },
    { name: 'Mizuki Kai', alias: 'snowman' },
    { name: 'David Person', alias: 'Dangerous 🐦' },
    { name: 'Zorian Facey', alias: 'VolcanoAshez' },
    { name: 'Christopher Nguyen', alias: 'peanut' },
    { name: 'Hannah Partigianoni', alias: 'HNineP' },
    { name: 'Trent Smart', alias: 'wasabiii' },
    { name: 'Taher Vahanvaty', alias: 'Big T' },
    { name: 'Alexander Vertikov', alias: 'A12 Verty' },
    { name: 'Oliver Villanueva', alias: 'OlliePop' },
    { name: 'Aidan Wang', alias: 'binary1011' },
    { name: 'Halleluiah Girum', alias: 'cr7goat' },
    { name: 'Eric Hu', alias: 'MooCow' },
    { name: 'Leanna Le', alias: 'Bobaaa' },
    { name: 'Sophia Li', alias: 'sli' },
    { name: 'Ikenna Odimegwu', alias: 'MoonRocket' },
    { name: 'Alexander Ong', alias: 'sedulba' },
    { name: 'Sophia Ordonez', alias: 'BluenoSoccer1' },
    { name: 'Sujith Pakala', alias: 'StagNation' },
    { name: 'Harrison Powe', alias: 'Collard_Greens' },
    { name: 'Nicolas Rombaut-Enriquez', alias: 'Zazarelle' },
    { name: 'Lily Zamora', alias: 'Purple Pancakes' },
    { name: 'Andrew Zhong', alias: 'LarrySummerstheGoat25' },
    { name: 'Nina Yuan Zhong', alias: 'Nani' },
    { name: 'Skye Stewart', alias: 'Chicken Joe' },
    { name: 'Natalie Chen', alias: 'Sushipasta' },
    { name: 'Miora Andriamahefa', alias: 'Rainy Day' },
    { name: 'Wei Yang Chan', alias: 'Duarte No1' },
    { name: 'Raquelle Barasa', alias: 'cottoncandyspark 🍭' },
    { name: 'Christopher Ho', alias: 'Penguin Vibes' },
    { name: 'Hans Xu', alias: 'iloveecon1500' },
    { name: 'Tatum Muller', alias: 'TM123' },
    { name: 'Henry Shan', alias: 'Chicken👹' },
    { name: 'Nate Schneider', alias: 'fernandofan21' },
    { name: 'Derrick Pennix', alias: 'Maximus Story' },
    { name: 'Brennon DeMeritt', alias: 'Sem Tres3' },
    { name: 'Eleonor Zok', alias: 'MatchaZen 🍵' },
    { name: 'Emily Mueller', alias: 'SailorBr19' },
    { name: 'Leah Derenge', alias: 'ice-cream cake' },
    { name: 'Emily Cha', alias: 'TiredSenior2025' },
    { name: 'Paula Suarez', alias: 'econstudent15' },
    { name: 'Efe Alpay', alias: 'Devious Deer' },
    { name: 'Theodore Carroll', alias: 'BearCracker' },
    { name: 'Helen Horangic', alias: 'Strange Bird' },
    { name: 'Sophia Healey', alias: 'Huzzah Maracas' },
    { name: 'Luis Gomez', alias: 'majayrie' },
    { name: 'Neni Alvarado', alias: '🦆' },
    { name: 'Jeffrey Liang', alias: 'Blockshoota10' },
    { name: 'Darian Jones', alias: 'Apple10Goat' },
    { name: 'Larissa Flora', alias: 'pele>messi' },
    { name: 'Isabella Banyasz', alias: 'redraspberry' },
    { name: 'Rina Shinozaki', alias: 'SmoothOperator 🏎️' },
    { name: 'Jeremy Lum', alias: 'Bread 🍞' },
    { name: 'Marilyn Abney', alias: 'MissMonroe' },
    { name: 'Alek Karagozyan', alias: 'TennisSleepRepeat' },
    { name: 'Julian Cronin', alias: 'Barack Obama' },
    { name: 'Ethan Davis', alias: 'Password🤯' },
    { name: 'Tyler Forman', alias: 'couloir' },
    { name: 'Sydney Fritz', alias: 'Goose 1' },
    { name: 'John Starman', alias: 'Squid23Streak' },
    { name: 'Jules de Beauport', alias: 'Debonaire Disaster' },
    { name: 'Nicholson Kanefield', alias: 'MrMan221' },
    { name: 'Michael Renoit', alias: 'BitcoinWins' },
    { name: 'Jessica Lin', alias: 'night owl' },
    { name: 'Samuel Carrillo', alias: 'Supple Thighs' },
    { name: 'Jonathan Lee', alias: 'Cornerstone' },
];
